/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author simon
 */
public class Interfaz extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        agregarresumen = new javax.swing.JButton();
        analizar = new javax.swing.JButton();
        buscarpalabraclave = new javax.swing.JButton();
        buscarautor = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        volveragregar = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        volveranalizar = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        volverbuscarpalabraclave = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        volverbuscarautor = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setBackground(new java.awt.Color(153, 153, 255));
        jTabbedPane1.setForeground(new java.awt.Color(0, 0, 0));

        jPanel2.setBackground(new java.awt.Color(51, 51, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("SOUTH LIBRARY");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Agregue su resumen y navegue por las diferentes pestañas...");
        jLabel2.setToolTipText("");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 530, 90));

        agregarresumen.setBackground(new java.awt.Color(153, 153, 255));
        agregarresumen.setForeground(new java.awt.Color(0, 0, 0));
        agregarresumen.setText("AGREGAR RESUMEN ");
        agregarresumen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarresumenActionPerformed(evt);
            }
        });
        jPanel2.add(agregarresumen, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 160, 40));

        analizar.setBackground(new java.awt.Color(153, 153, 255));
        analizar.setForeground(new java.awt.Color(0, 0, 0));
        analizar.setText("ANALIZAR RESUMEN ");
        analizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                analizarActionPerformed(evt);
            }
        });
        jPanel2.add(analizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 160, 40));

        buscarpalabraclave.setBackground(new java.awt.Color(153, 153, 255));
        buscarpalabraclave.setForeground(new java.awt.Color(0, 0, 0));
        buscarpalabraclave.setText("BUSCAR POR P.CLAVE");
        buscarpalabraclave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarpalabraclaveActionPerformed(evt);
            }
        });
        jPanel2.add(buscarpalabraclave, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 160, 40));

        buscarautor.setBackground(new java.awt.Color(153, 153, 255));
        buscarautor.setForeground(new java.awt.Color(0, 0, 0));
        buscarautor.setText("BUSCAR POR AUTOR");
        buscarautor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarautorActionPerformed(evt);
            }
        });
        jPanel2.add(buscarautor, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 160, 40));

        jButton1.setBackground(new java.awt.Color(153, 153, 255));
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("SALIR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 350, 100, 40));

        jTabbedPane1.addTab("INICIO", jPanel2);

        jPanel3.setBackground(new java.awt.Color(51, 51, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        volveragregar.setBackground(new java.awt.Color(153, 153, 255));
        volveragregar.setForeground(new java.awt.Color(0, 0, 0));
        volveragregar.setText("VOLVER");
        volveragregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volveragregarActionPerformed(evt);
            }
        });
        jPanel3.add(volveragregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 480, 100, 30));

        jTabbedPane1.addTab("ADD RESUMEN", jPanel3);

        jPanel4.setBackground(new java.awt.Color(51, 51, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        volveranalizar.setBackground(new java.awt.Color(153, 153, 255));
        volveranalizar.setForeground(new java.awt.Color(0, 0, 0));
        volveranalizar.setText("VOLVER");
        volveranalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volveranalizarActionPerformed(evt);
            }
        });
        jPanel4.add(volveranalizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 480, 100, 40));

        jTabbedPane1.addTab("ANALIZAR RESUMEN", jPanel4);

        jPanel5.setBackground(new java.awt.Color(51, 51, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        volverbuscarpalabraclave.setBackground(new java.awt.Color(153, 153, 255));
        volverbuscarpalabraclave.setForeground(new java.awt.Color(0, 0, 0));
        volverbuscarpalabraclave.setText("VOLVER");
        volverbuscarpalabraclave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverbuscarpalabraclaveActionPerformed(evt);
            }
        });
        jPanel5.add(volverbuscarpalabraclave, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 480, 90, 30));

        jTabbedPane1.addTab("BUSCAR P.CLAVE", jPanel5);

        jPanel6.setBackground(new java.awt.Color(51, 51, 255));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        volverbuscarautor.setBackground(new java.awt.Color(153, 153, 255));
        volverbuscarautor.setForeground(new java.awt.Color(0, 0, 0));
        volverbuscarautor.setText("VOLVER");
        volverbuscarautor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverbuscarautorActionPerformed(evt);
            }
        });
        jPanel6.add(volverbuscarautor, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 480, 100, 30));

        jTabbedPane1.addTab("BUSCAR P.AUTOR", jPanel6);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 751, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buscarpalabraclaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarpalabraclaveActionPerformed
        jTabbedPane1.setSelectedIndex(3);
    }//GEN-LAST:event_buscarpalabraclaveActionPerformed

    private void buscarautorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarautorActionPerformed
         jTabbedPane1.setSelectedIndex(4);
    }//GEN-LAST:event_buscarautorActionPerformed

    private void agregarresumenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarresumenActionPerformed
        jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_agregarresumenActionPerformed

    private void analizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_analizarActionPerformed
         jTabbedPane1.setSelectedIndex(2);
    }//GEN-LAST:event_analizarActionPerformed

    private void volveragregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volveragregarActionPerformed
         jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_volveragregarActionPerformed

    private void volverbuscarautorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverbuscarautorActionPerformed
         jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_volverbuscarautorActionPerformed

    private void volverbuscarpalabraclaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverbuscarpalabraclaveActionPerformed
         jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_volverbuscarpalabraclaveActionPerformed

    private void volveranalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volveranalizarActionPerformed
         jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_volveranalizarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarresumen;
    private javax.swing.JButton analizar;
    private javax.swing.JButton buscarautor;
    private javax.swing.JButton buscarpalabraclave;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton volveragregar;
    private javax.swing.JButton volveranalizar;
    private javax.swing.JButton volverbuscarautor;
    private javax.swing.JButton volverbuscarpalabraclave;
    // End of variables declaration//GEN-END:variables
}
